### ISSUE TITLE
active_chart_interval not found

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#32] opened 2021-11-09 20:16 UTC
When trying to backtest a strategy I'm encountering the following error.

```
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 3959, in back_test_strategy_symbol
    elem_interval = find_element(browser, css_selectors['active_chart_interval'])
  File "/kairos/tv/tv.py", line 444, in find_element
    element = WebDriverWait(browser, delay).until(
  File "/usr/local/lib/python3.9/site-packages/selenium-3.141.0-py3.9.egg/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
```

I'm on the most recent version 2.57.

**Comment by timelyart** [comment] 2021-11-10 11:44
I was unable to reproduce this. 

Do you have multiple charts on your layout?
What interval were you trying to set?

**Comment by marcfon** [comment] 2021-11-10 12:05
I just have 1 chart on my layout. And as far as I know I'm not actively setting any intervals.

I've stripped my `strategies.yaml` down to the bare minimum for this test.

```
charts:
- url: https://www.tradingview.com/chart/XXXXXXX/
  timeframes: [1 hour]
  watchlists: [QFL]
  - name: "QFL3C"
    pane_index: 0
    inputs: {}
    properties: {}
webdriver:
  run-in-background: yes
```

It's the first time that I'm trying to set this up so really curious what I've missed in the process.

**Comment by marcfon** [comment] 2021-11-10 12:18
When I run kairos with more debug info I see that this message appears in the log quite a few times just before the `active_chart_interval` error is thrown. Could this be related?

```
2021-11-10 13:15:29.311 DEBUG remote_connection - _request: POST http://127.0.0.1:63325/session/2acae7787c4e6486aadeb7691f4d0880/element {"using": "css selector", "value": "div[id=\"header-toolbar-intervals\"] div[class*=\"isActive\"] > div > div"}
2021-11-10 13:15:29.317 DEBUG connectionpool - _make_request: http://127.0.0.1:63325 "POST /session/2acae7787c4e6486aadeb7691f4d0880/element HTTP/1.1" 404 1983

```

Also quite a few 404 errors on this one:

```
2021-11-10 13:22:40.017 DEBUG remote_connection - _request: POST http://127.0.0.1:63629/session/b32c9b02d34dbb283f2cd3e608a25502/element {"using": "css selector", "value": "div[data-name=\"backtesting\"][data-active=\"false\"]"}
2021-11-10 13:22:40.023 DEBUG connectionpool - _make_request: http://127.0.0.1:63629 "POST /session/b32c9b02d34dbb283f2cd3e608a25502/element HTTP/1.1" 404 1963

```

**Comment by timelyart** [comment] 2021-11-10 13:58
I was able to reproduce this when I had no favorite time intervals defined in TradingView. Expect a fix soon.

**Comment by marcfon** [comment] 2021-11-10 14:09
I can confirm that favoriting a timeframe gets rid of the active_chart_interval error. 

So to test I did favorite a timeframe and now I'm seeing a different error.

```
2021-11-10 15:06:49.546 ERROR tv - retry_back_test_strategy_symbol: '>' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/Users/marcfonteijn/stack/016 - investing/kairos/tv/tv.py", line 3992, in back_test_strategy_symbol
    if key == 'performance_summary_total_closed_trades' and config.has_option('backtesting', 'threshold') and config.getint('backtesting', 'threshold') > value:
TypeError: '>' not supported between instances of 'int' and 'str'
```

**Comment by marcfon** [comment] 2021-11-10 14:09
I can confirm that favoriting a timeframe gets rid of the active_chart_interval error.

So to test I did favorite a timeframe and now I'm seeing a different error.

```
2021-11-10 15:06:49.546 ERROR tv - retry_back_test_strategy_symbol: '>' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 3992, in back_test_strategy_symbol
    if key == 'performance_summary_total_closed_trades' and config.has_option('backtesting', 'threshold') and config.getint('backtesting', 'threshold') > value:
TypeError: '>' not supported between instances of 'int' and 'str'
```

**Comment by timelyart** [comment] 2021-11-10 14:31
> So to test I did favorite a timeframe and now I'm seeing a different error.
> 
> ```
> 2021-11-10 15:06:49.546 ERROR tv - retry_back_test_strategy_symbol: '>' not supported between instances of 'int' and 'str'
> Traceback (most recent call last):
>   File "/kairos/tv/tv.py", line 3992, in back_test_strategy_symbol
>     if key == 'performance_summary_total_closed_trades' and config.has_option('backtesting', 'threshold') and config.getint('backtesting', 'threshold') > value:
> TypeError: '>' not supported between instances of 'int' and 'str'
> ```

What is the value for `threshold` under `[backtesting]` in your **kairos.cfg**?

**Comment by timelyart** [comment] 2021-11-10 14:31
> I was able to reproduce this when I had no favorite time intervals defined in TradingView. Expect a fix soon.

Fixed in [release v2.59](https://github.com/timelyart/Kairos/releases/tag/v2.59).

**Comment by marcfon** [comment] 2021-11-10 14:38
> What is the value for `threshold` under `[backtesting]` in your **kairos.cfg**?

It's set to 1.

I can confirm that v2.59 works without having a timeframe favorited.

**Comment by timelyart** [comment] 2021-11-10 14:44
> > What is the value for `threshold` under `[backtesting]` in your **kairos.cfg**?
> 
> It's set to 1.

Opened a separate issue for this bug. See issue #35.

> 
> I can confirm that v2.59 works without having a timeframe favorited.

Issue closed.

**Closed as completed by timelyart** 2021-11-10 14:44 UTC
Labels: bug
