### ISSUE TITLE
Select fields not working properly (previously known as Alerts not configuring correctly)

### ISSUE THREAD

**Issue by joowen** [timelyart/Kairos#9] opened 2020-04-20 02:44 UTC
I am attaching screenshot and video link download so you can review. Let me know if you have any questions.

https://we.tl/t-1nRycztI7m

<img width="1280" alt="Screen Shot 2020-04-19 at 10 18 26 PM" src="https://user-images.githubusercontent.com/43221151/79709025-199ee780-828f-11ea-9ba8-f95af57e2ca5.png">

**Comment by timelyart** [comment] 2020-04-20 08:44
TV is running really slowly on your mac. Kairos can't find web elements in time. You may try to heighten the `[delays]` in your **kairos.cfg** but you won't have a good experience with a computer running TV that slow. Do you have `[webdriver] -> share_user_data` enabled? This will create a separate user data folder for chrome to store it's session (including cache) that *might* speed things up.

**Comment by joowen** [comment] 2020-04-20 08:47
Maybe you didn't see what was going on. It was not adding the alerts correctly. For example it was not adding the item in the second drop down correctly, and not adding the once per minute either.

**Comment by timelyart** [comment] 2020-04-20 08:52
Please share your YAML file so that I can see how the alert was set up. Make sure to remove any personal details.

**Comment by timelyart** [comment] 2020-04-20 08:56
One more question, do other alerts work for you (e.g. YAML/_alert.yaml)?

**Comment by joowen** [comment] 2020-04-20 09:05
I did not try any other yaml files. I am attaching my yaml file here.
https://we.tl/t-txFymv99Ew

[alert_davo.zip](https://github.com/timelyart/Kairos/files/4502462/alert_davo.zip)

**Comment by timelyart** [comment] 2020-04-20 09:25
I can't test it for myself since it's an invite only script. Can you make a chart with the Golden Cross indicator by Chuckytuh, then configure and run YAML\_alert.yaml?

On a side note, the expiration date/time is blank and so I worry that the alert dialog on TV isn't fully loaded and therefore the condition `"Short TP 5"` cannot be found.

**Comment by joowen** [comment] 2020-04-20 10:03
Ok so I did the golden cross indicator and its working. It also selects a default expiration time when that field is left blank.

However that just makes me confused about why it didn't work for my indicator as everything to my knowledge has been calibrated appropriately. If you want to get a trial to the indicator and maybe see what's going on its here (they'll give you indicator access within 15 minutes):

https://www.hiubris-indicators.com/trial/

**Comment by timelyart** [comment] 2020-04-20 10:21
Can you zip your latest log file of alert_davo.yaml and post it here (should be under Kairos/log)? It may provide clues as why it fails to set the second condition.

**Comment by joowen** [comment] 2020-04-20 10:27
Attaching here. I should note I was exiting it prematurely by closing the Chrome window when running into the errors
[alert_davo.yaml.log](https://github.com/timelyart/Kairos/files/4502787/alert_davo.yaml.log)
.

**Comment by timelyart** [comment] 2020-04-20 10:35
Well, I don't see any evidence it has to do with your configuration. Kairos would spit out a specific message: *Invalid condition (2): {your condition} in yaml definition {your yaml file}*. 

So, it's back to 'Do you have `[webdriver] -> share_user_data` enabled?' If not, and you were using Chrome whilst Kairos is running then you might have interfered with the process.

**Comment by joowen** [comment] 2020-04-20 10:40
Where/how do i configure the web driver?

**Comment by joowen** [comment] 2020-04-20 10:46
Also I do not think or believe there is a real speed issue. It was very slow when recording because of the actual screen recorder itself. The software worked perfectly fine when making the watchlist and also alerts for the Golden Cross indicator.

**Comment by timelyart** [comment] 2020-04-20 10:50
> 
> 
> Where/how do i configure the web driver?

In your **kairos.cfg**, which you can find directly under your Kairos directory.

**Comment by joowen** [comment] 2020-04-20 10:59
I checked Kairos.cfg, do not see that option.

**Comment by joowen** [comment] 2020-04-20 11:00
Oh ok, share user data to true. I see it now

**Comment by joowen** [comment] 2020-04-20 11:06
I'm still running into the exact same issue... it selects the indicator but does not select Short TP 5, and either refreshes the page or saves the alert like that.

**Comment by joowen** [comment] 2020-04-20 12:21
I think i discovered what the issue is. Its unable to scroll down. I tested this by using Long TP 5 which did not require a scroll and it worked.

**Comment by timelyart** [comment] 2020-04-20 12:26
TV probably changed the way how the select fields are loaded. Thanks for finding that out.

**Comment by timelyart** [comment] 2020-04-20 14:23
I cannot reproduce this issue, i.e. I can successfully set the bottom option of a list of 15 options. Can you post a picture with all of the options? Again, your log file might provide clues. Can you post that file as well.

**Comment by joowen** [comment] 2020-04-20 14:46
Attaching files here. Again all I changed in the yaml file I sent you to get it to work was I made it Long TP 5 vs Short TP 5
![Screen Shot 2020-04-20 at 10 38 24 AM](https://user-images.githubusercontent.com/43221151/79764982-0c681400-82f4-11ea-85bd-b2eaa6c9ecfb.png)
![Screen Shot 2020-04-20 at 10 37 33 AM](https://user-images.githubusercontent.com/43221151/79764987-0d994100-82f4-11ea-9b4b-ee203239a0d9.png)


[alert_davo.yaml.log](https://github.com/timelyart/Kairos/files/4504168/alert_davo.yaml.log)
![Screen Shot 2020-04-20 at 10 37 16 AM](https://user-images.githubusercontent.com/43221151/79764956-06723300-82f4-11ea-9461-a7d58cb8d0ab.png)
![Screen Shot 2020-04-20 at 10 36 56 AM](https://user-images.githubusercontent.com/43221151/79764972-0a05ba00-82f4-11ea-87ca-b7608a35264e.png)

**Comment by timelyart** [comment] 2020-04-20 16:09
According to the log file, there were no errors up until NYSE:AXL (line 58). After which something happened, and at some time after Chrome seemingly was closed (line 256). When I read the log, I cannot help but think that something is interfering with the web browser's process. I don't see any hints of Kairos not finding elements at all (*TimeoutException*) or just not the specific condition (*Invalid condition (2): {your condition} in yaml definition {your yaml file}*).

Please update to v2.18 set `[webdriver] -> user_data_directory` and `[webdriver] -> share_user_data` in **kairos.cfg**. Try again, and if it doesn't work, post the log file as well as any screenshot made by Kairos.

**Comment by joowen** [comment] 2020-04-20 18:16
Am I supposed to leave user data directory blank?

**Comment by joowen** [comment] 2020-04-20 18:24
<img width="1280" alt="Screen Shot 2020-04-20 at 2 21 14 PM" src="https://user-images.githubusercontent.com/43221151/79785926-a9d24080-8312-11ea-8d90-9a67ef37abf4.png">

Updated everything, still same issue

**Comment by timelyart** [comment] 2020-04-20 19:02
> 
> 
> Am I supposed to leave user data directory blank?

Nope. It should refer to wherever the user data directory of your browser is. I could have done a better job on the documentation here. 

That being said, I have reproduced and identified the issue using an indicator with a very large set of options. As soon as I have tested it I'll bring out a patch. Thanks again for creating the issue and your patience resolving this matter.

**Comment by timelyart** [comment] 2020-04-20 19:12
Fixed in [v2.19](https://github.com/timelyart/Kairos/releases/tag/v2.19)

**Closed as completed by timelyart** 2020-04-20 19:12 UTC
Labels: bug

**Comment by joowen** [comment] 2020-04-20 19:35
Ok wonderful finally working. In what format do I insert the expiration in the yaml file?

**Comment by timelyart** [comment] 2020-04-20 20:16
From the comment above the setting:

```
# Future date time (note TradingView uses local time to set expiration and Kairos will check the computer's time against TV expiration).
# Format it in yyyy-mm-dd hh:mm, or n where n is the number of days (note that trading view has a maximum of 60).
# time: 2019-05-19 13:42, or delta in minutes (max 86400, or 60 days), or leave empty to use TradingView's default of 30 days (somewhat improves performance).
```

**Comment by joowen** [comment] 2020-04-20 20:23
Perfect. I kept putting it in front of expiration and the command would abort. Finally working!
